test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitflow_dev
  pool: 2
  username: root
  password:
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bitflow_dev
  pool: 20
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock