require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BankaccountsController do

  # This should return the minimal set of attributes required to create a valid
  # Bankaccount. As you add validations to Bankaccount, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bankaccounts as @bankaccounts" do
      bankaccount = Bankaccount.create! valid_attributes
      get :index
      assigns(:bankaccounts).should eq([bankaccount])
    end
  end

  describe "GET show" do
    it "assigns the requested bankaccount as @bankaccount" do
      bankaccount = Bankaccount.create! valid_attributes
      get :show, :id => bankaccount.id.to_s
      assigns(:bankaccount).should eq(bankaccount)
    end
  end

  describe "GET new" do
    it "assigns a new bankaccount as @bankaccount" do
      get :new
      assigns(:bankaccount).should be_a_new(Bankaccount)
    end
  end

  describe "GET edit" do
    it "assigns the requested bankaccount as @bankaccount" do
      bankaccount = Bankaccount.create! valid_attributes
      get :edit, :id => bankaccount.id.to_s
      assigns(:bankaccount).should eq(bankaccount)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bankaccount" do
        expect {
          post :create, :bankaccount => valid_attributes
        }.to change(Bankaccount, :count).by(1)
      end

      it "assigns a newly created bankaccount as @bankaccount" do
        post :create, :bankaccount => valid_attributes
        assigns(:bankaccount).should be_a(Bankaccount)
        assigns(:bankaccount).should be_persisted
      end

      it "redirects to the created bankaccount" do
        post :create, :bankaccount => valid_attributes
        response.should redirect_to(Bankaccount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bankaccount as @bankaccount" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bankaccount.any_instance.stub(:save).and_return(false)
        post :create, :bankaccount => {}
        assigns(:bankaccount).should be_a_new(Bankaccount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bankaccount.any_instance.stub(:save).and_return(false)
        post :create, :bankaccount => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bankaccount" do
        bankaccount = Bankaccount.create! valid_attributes
        # Assuming there are no other bankaccounts in the database, this
        # specifies that the Bankaccount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bankaccount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bankaccount.id, :bankaccount => {'these' => 'params'}
      end

      it "assigns the requested bankaccount as @bankaccount" do
        bankaccount = Bankaccount.create! valid_attributes
        put :update, :id => bankaccount.id, :bankaccount => valid_attributes
        assigns(:bankaccount).should eq(bankaccount)
      end

      it "redirects to the bankaccount" do
        bankaccount = Bankaccount.create! valid_attributes
        put :update, :id => bankaccount.id, :bankaccount => valid_attributes
        response.should redirect_to(bankaccount)
      end
    end

    describe "with invalid params" do
      it "assigns the bankaccount as @bankaccount" do
        bankaccount = Bankaccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bankaccount.any_instance.stub(:save).and_return(false)
        put :update, :id => bankaccount.id.to_s, :bankaccount => {}
        assigns(:bankaccount).should eq(bankaccount)
      end

      it "re-renders the 'edit' template" do
        bankaccount = Bankaccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bankaccount.any_instance.stub(:save).and_return(false)
        put :update, :id => bankaccount.id.to_s, :bankaccount => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bankaccount" do
      bankaccount = Bankaccount.create! valid_attributes
      expect {
        delete :destroy, :id => bankaccount.id.to_s
      }.to change(Bankaccount, :count).by(-1)
    end

    it "redirects to the bankaccounts list" do
      bankaccount = Bankaccount.create! valid_attributes
      delete :destroy, :id => bankaccount.id.to_s
      response.should redirect_to(bankaccounts_url)
    end
  end

end
