require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BtcFundTransfersController do

  # This should return the minimal set of attributes required to create a valid
  # BtcFundTransfer. As you add validations to BtcFundTransfer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all btc_fund_transfers as @btc_fund_transfers" do
      btc_fund_transfer = BtcFundTransfer.create! valid_attributes
      get :index
      assigns(:btc_fund_transfers).should eq([btc_fund_transfer])
    end
  end

  describe "GET show" do
    it "assigns the requested btc_fund_transfer as @btc_fund_transfer" do
      btc_fund_transfer = BtcFundTransfer.create! valid_attributes
      get :show, :id => btc_fund_transfer.id.to_s
      assigns(:btc_fund_transfer).should eq(btc_fund_transfer)
    end
  end

  describe "GET new" do
    it "assigns a new btc_fund_transfer as @btc_fund_transfer" do
      get :new
      assigns(:btc_fund_transfer).should be_a_new(BtcFundTransfer)
    end
  end

  describe "GET edit" do
    it "assigns the requested btc_fund_transfer as @btc_fund_transfer" do
      btc_fund_transfer = BtcFundTransfer.create! valid_attributes
      get :edit, :id => btc_fund_transfer.id.to_s
      assigns(:btc_fund_transfer).should eq(btc_fund_transfer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BtcFundTransfer" do
        expect {
          post :create, :btc_fund_transfer => valid_attributes
        }.to change(BtcFundTransfer, :count).by(1)
      end

      it "assigns a newly created btc_fund_transfer as @btc_fund_transfer" do
        post :create, :btc_fund_transfer => valid_attributes
        assigns(:btc_fund_transfer).should be_a(BtcFundTransfer)
        assigns(:btc_fund_transfer).should be_persisted
      end

      it "redirects to the created btc_fund_transfer" do
        post :create, :btc_fund_transfer => valid_attributes
        response.should redirect_to(BtcFundTransfer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved btc_fund_transfer as @btc_fund_transfer" do
        # Trigger the behavior that occurs when invalid params are submitted
        BtcFundTransfer.any_instance.stub(:save).and_return(false)
        post :create, :btc_fund_transfer => {}
        assigns(:btc_fund_transfer).should be_a_new(BtcFundTransfer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BtcFundTransfer.any_instance.stub(:save).and_return(false)
        post :create, :btc_fund_transfer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested btc_fund_transfer" do
        btc_fund_transfer = BtcFundTransfer.create! valid_attributes
        # Assuming there are no other btc_fund_transfers in the database, this
        # specifies that the BtcFundTransfer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BtcFundTransfer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => btc_fund_transfer.id, :btc_fund_transfer => {'these' => 'params'}
      end

      it "assigns the requested btc_fund_transfer as @btc_fund_transfer" do
        btc_fund_transfer = BtcFundTransfer.create! valid_attributes
        put :update, :id => btc_fund_transfer.id, :btc_fund_transfer => valid_attributes
        assigns(:btc_fund_transfer).should eq(btc_fund_transfer)
      end

      it "redirects to the btc_fund_transfer" do
        btc_fund_transfer = BtcFundTransfer.create! valid_attributes
        put :update, :id => btc_fund_transfer.id, :btc_fund_transfer => valid_attributes
        response.should redirect_to(btc_fund_transfer)
      end
    end

    describe "with invalid params" do
      it "assigns the btc_fund_transfer as @btc_fund_transfer" do
        btc_fund_transfer = BtcFundTransfer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BtcFundTransfer.any_instance.stub(:save).and_return(false)
        put :update, :id => btc_fund_transfer.id.to_s, :btc_fund_transfer => {}
        assigns(:btc_fund_transfer).should eq(btc_fund_transfer)
      end

      it "re-renders the 'edit' template" do
        btc_fund_transfer = BtcFundTransfer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BtcFundTransfer.any_instance.stub(:save).and_return(false)
        put :update, :id => btc_fund_transfer.id.to_s, :btc_fund_transfer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested btc_fund_transfer" do
      btc_fund_transfer = BtcFundTransfer.create! valid_attributes
      expect {
        delete :destroy, :id => btc_fund_transfer.id.to_s
      }.to change(BtcFundTransfer, :count).by(-1)
    end

    it "redirects to the btc_fund_transfers list" do
      btc_fund_transfer = BtcFundTransfer.create! valid_attributes
      delete :destroy, :id => btc_fund_transfer.id.to_s
      response.should redirect_to(btc_fund_transfers_url)
    end
  end

end
