require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FundDepositsController do

  # This should return the minimal set of attributes required to create a valid
  # FundDeposit. As you add validations to FundDeposit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all fund_deposits as @fund_deposits" do
      fund_deposit = FundDeposit.create! valid_attributes
      get :index
      assigns(:fund_deposits).should eq([fund_deposit])
    end
  end

  describe "GET show" do
    it "assigns the requested fund_deposit as @fund_deposit" do
      fund_deposit = FundDeposit.create! valid_attributes
      get :show, :id => fund_deposit.id.to_s
      assigns(:fund_deposit).should eq(fund_deposit)
    end
  end

  describe "GET new" do
    it "assigns a new fund_deposit as @fund_deposit" do
      get :new
      assigns(:fund_deposit).should be_a_new(FundDeposit)
    end
  end

  describe "GET edit" do
    it "assigns the requested fund_deposit as @fund_deposit" do
      fund_deposit = FundDeposit.create! valid_attributes
      get :edit, :id => fund_deposit.id.to_s
      assigns(:fund_deposit).should eq(fund_deposit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FundDeposit" do
        expect {
          post :create, :fund_deposit => valid_attributes
        }.to change(FundDeposit, :count).by(1)
      end

      it "assigns a newly created fund_deposit as @fund_deposit" do
        post :create, :fund_deposit => valid_attributes
        assigns(:fund_deposit).should be_a(FundDeposit)
        assigns(:fund_deposit).should be_persisted
      end

      it "redirects to the created fund_deposit" do
        post :create, :fund_deposit => valid_attributes
        response.should redirect_to(FundDeposit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fund_deposit as @fund_deposit" do
        # Trigger the behavior that occurs when invalid params are submitted
        FundDeposit.any_instance.stub(:save).and_return(false)
        post :create, :fund_deposit => {}
        assigns(:fund_deposit).should be_a_new(FundDeposit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FundDeposit.any_instance.stub(:save).and_return(false)
        post :create, :fund_deposit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fund_deposit" do
        fund_deposit = FundDeposit.create! valid_attributes
        # Assuming there are no other fund_deposits in the database, this
        # specifies that the FundDeposit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FundDeposit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => fund_deposit.id, :fund_deposit => {'these' => 'params'}
      end

      it "assigns the requested fund_deposit as @fund_deposit" do
        fund_deposit = FundDeposit.create! valid_attributes
        put :update, :id => fund_deposit.id, :fund_deposit => valid_attributes
        assigns(:fund_deposit).should eq(fund_deposit)
      end

      it "redirects to the fund_deposit" do
        fund_deposit = FundDeposit.create! valid_attributes
        put :update, :id => fund_deposit.id, :fund_deposit => valid_attributes
        response.should redirect_to(fund_deposit)
      end
    end

    describe "with invalid params" do
      it "assigns the fund_deposit as @fund_deposit" do
        fund_deposit = FundDeposit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FundDeposit.any_instance.stub(:save).and_return(false)
        put :update, :id => fund_deposit.id.to_s, :fund_deposit => {}
        assigns(:fund_deposit).should eq(fund_deposit)
      end

      it "re-renders the 'edit' template" do
        fund_deposit = FundDeposit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FundDeposit.any_instance.stub(:save).and_return(false)
        put :update, :id => fund_deposit.id.to_s, :fund_deposit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fund_deposit" do
      fund_deposit = FundDeposit.create! valid_attributes
      expect {
        delete :destroy, :id => fund_deposit.id.to_s
      }.to change(FundDeposit, :count).by(-1)
    end

    it "redirects to the fund_deposits list" do
      fund_deposit = FundDeposit.create! valid_attributes
      delete :destroy, :id => fund_deposit.id.to_s
      response.should redirect_to(fund_deposits_url)
    end
  end

end
