require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserWalletsController do

  # This should return the minimal set of attributes required to create a valid
  # UserWallet. As you add validations to UserWallet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all user_wallets as @user_wallets" do
      user_wallet = UserWallet.create! valid_attributes
      get :index
      assigns(:user_wallets).should eq([user_wallet])
    end
  end

  describe "GET show" do
    it "assigns the requested user_wallet as @user_wallet" do
      user_wallet = UserWallet.create! valid_attributes
      get :show, :id => user_wallet.id.to_s
      assigns(:user_wallet).should eq(user_wallet)
    end
  end

  describe "GET new" do
    it "assigns a new user_wallet as @user_wallet" do
      get :new
      assigns(:user_wallet).should be_a_new(UserWallet)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_wallet as @user_wallet" do
      user_wallet = UserWallet.create! valid_attributes
      get :edit, :id => user_wallet.id.to_s
      assigns(:user_wallet).should eq(user_wallet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserWallet" do
        expect {
          post :create, :user_wallet => valid_attributes
        }.to change(UserWallet, :count).by(1)
      end

      it "assigns a newly created user_wallet as @user_wallet" do
        post :create, :user_wallet => valid_attributes
        assigns(:user_wallet).should be_a(UserWallet)
        assigns(:user_wallet).should be_persisted
      end

      it "redirects to the created user_wallet" do
        post :create, :user_wallet => valid_attributes
        response.should redirect_to(UserWallet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_wallet as @user_wallet" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserWallet.any_instance.stub(:save).and_return(false)
        post :create, :user_wallet => {}
        assigns(:user_wallet).should be_a_new(UserWallet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserWallet.any_instance.stub(:save).and_return(false)
        post :create, :user_wallet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_wallet" do
        user_wallet = UserWallet.create! valid_attributes
        # Assuming there are no other user_wallets in the database, this
        # specifies that the UserWallet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserWallet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => user_wallet.id, :user_wallet => {'these' => 'params'}
      end

      it "assigns the requested user_wallet as @user_wallet" do
        user_wallet = UserWallet.create! valid_attributes
        put :update, :id => user_wallet.id, :user_wallet => valid_attributes
        assigns(:user_wallet).should eq(user_wallet)
      end

      it "redirects to the user_wallet" do
        user_wallet = UserWallet.create! valid_attributes
        put :update, :id => user_wallet.id, :user_wallet => valid_attributes
        response.should redirect_to(user_wallet)
      end
    end

    describe "with invalid params" do
      it "assigns the user_wallet as @user_wallet" do
        user_wallet = UserWallet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserWallet.any_instance.stub(:save).and_return(false)
        put :update, :id => user_wallet.id.to_s, :user_wallet => {}
        assigns(:user_wallet).should eq(user_wallet)
      end

      it "re-renders the 'edit' template" do
        user_wallet = UserWallet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserWallet.any_instance.stub(:save).and_return(false)
        put :update, :id => user_wallet.id.to_s, :user_wallet => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_wallet" do
      user_wallet = UserWallet.create! valid_attributes
      expect {
        delete :destroy, :id => user_wallet.id.to_s
      }.to change(UserWallet, :count).by(-1)
    end

    it "redirects to the user_wallets list" do
      user_wallet = UserWallet.create! valid_attributes
      delete :destroy, :id => user_wallet.id.to_s
      response.should redirect_to(user_wallets_url)
    end
  end

end
